### ISSUE TITLE
Switching CTRL and FUN1 leads to nonfunctional CTRL

### ISSUE THREAD

**Issue by tkling** [kiibohd/KiiConf#12]
My apologies if this is the wrong repo for this issue - feel free to direct me to where it should go and I'll happily move it over!

I have an MD1, hacker layout.

I used Kiiconf to switch the position of CTRL and FUN1, in addition to a couple other edits. Here's my resulting layer 0 KLL file that came from Kiiconf:
```
U"CTRL" : U"FUN1";
U"FUNCTION1" : CONS"PAUSEPLAY";
U"FUN1" : U"CTRL";
U"RGUI" : U"FUN1";
U"RALT" : U"RGUI";
```
Everything seems to be working fine, minus my control keys (left and right) :(

Here's a screen shot of Kiiconf to give a more direct idea of what I was trying to do:
![screen shot 2015-09-18 at 4 10 26 pm](https://cloud.githubusercontent.com/assets/1123917/9969944/d40773b0-5e1f-11e5-8325-ad30f387a029.png)
I'm going to be looking into this more over the weekend, figured I would open this up to see if any quick solutions were already known, though. I figure if I just write my own KLL from the ground up and compile I could probably avoid this issue, I'd love to use the kiiconf convenience though!

Thanks in advance :metal:

**Comment by tkling** [comment]
Not sure if it would affect anything, but for reference I used the deployed version at http://configurator.input.club/

**Comment by haata** [comment]
I'm looking at Configurator related things for ErgoDox this weekend, so I should be able to look at this.
Would you mind sending me the 'download firmware' filename for your configuration? Usually MD1-Standard-<long hash number>.zip
With this I can find your configuration and try to debug it on my end.

**Comment by tkling** [comment]
MD1-Hacker-78a6a857b14a85b96c59bb1628b0fdc2.zip

Thanks for taking a look!

**Comment by haata** [comment]
Found the bug, working on a fix.

**Comment by haata** [comment]
I pushed a fix last night, should've fix the issue.
Let me know if there are still any issues. :D

**Comment by tkling** [comment]
That's awesome, thanks! I'll pull down a fresh kiiconf .zip and flash soon; if anything comes up I'll be back :)
