### ISSUE TITLE
Add support for ISO key 0x64

### ISSUE THREAD

**Issue by sigboe** [kiibohd/KiiConf#13]
Unable to set ISO key 0x64 in the configurator. This is the key that is extra on an ISO keyboard compared to an ANSI keyboard located right of the left shift. For UK ISO this is the `\ |` key. In my particular case I use Norwegian layouts in my OS and this key is then the `< >` key. 

I presume as a workaround when I get my Infinity ErogDox and Infinity 60% I can manually edit the configurator file and add this key before flashing the configuration, but I don't have my keyboards yet so I have not tried.

Please fix, or if that takes time advice in this matter. Regards!

**Comment by haata** [comment]
Ah, interesting. Yep, definitely important, I can see how the configurator would get mixed up in this case.

I'll add a special button below for this key.

**Comment by sigboe** [comment]
Thanks @haata I really appreciate it! I was a bit worried how I would write heart symbols for a moment there! Cant wait to soon get my keyboards from Massdrop, just didn't make the first round of LCDs for the ErgoDox, and the 60% is also almost shipping.

**Comment by haata** [comment]
Np. The latest rumours say that the 2nd round will be shipping out late next week :D 

Fixed.
c2d5f9109b8aa05fc416d1a1258d7472aef30f4d

Just for the heck of it, I also added buttons for most of the international keys. There are a few that I haven't added (but I'm not even sure they are used anymore, can add if needed).
I also snuck in some LED brightness control.

**Comment by sigboe** [comment]
@haata thanks! Thats a great update :smile: And I really looking forward to starting to solder the keyboard! 

Now I just need to pick up a new soldering, since mine is near dying.
