### ISSUE TITLE
Configurator not including some parts of layers in .bin files

### ISSUE THREAD

**Issue by kevin349** [kiibohd/KiiConf#15]
I am trying to generate the firmware for the below set up.  When I flash however, locking to layer two does not result in the QWERTY layout I am expecting.  Instead it keeps the QDRWB layout i have on main layer.  

Note some keys are mapping up.  This includes the prnt screen key is working on layer 2, and anything not in the main 1x key region.

See the following json for a set up:
https://gist.github.com/anonymous/0b93e7a585fa8f647622

**Comment by basepi** [comment]
@kevin349 Could you move your json into a gist.github.com so it doesn't take so much scrolling to see replies to the issue? You can edit your post with the pencil icon in the top right.

I should note I'm running into an issue like this. I opened a forum thread: http://input.club/forums/topic/any-layer-2-wont-work

Here's my json: https://gist.github.com/basepi/65a535da970ff43a01a2

And here's the KLL for layer 2, which should be QWERTY but is not. https://gist.github.com/basepi/036f7a61cc69c1fed761

Obviously the KLL is not being created correctly. Keep me posted if there's anything more I can do to help diagnose the issue!

**Comment by OvahKeel** [comment]
Should be fixed with 1a06f3f
