### ISSUE TITLE
The calculator media key writes O

### ISSUE THREAD

**Issue by dumle29** [kiibohd/KiiConf#2]
So assigning a key to be a calculator key, just writes O. Scancode for calculator key: 0x192 Scacode for O 0x12

Here's the offending layout:
![image](https://cloud.githubusercontent.com/assets/2756925/7749248/1549e950-ffcc-11e4-818f-9ba2f8622ae2.png)

And the offending KLL is here:
https://mega.co.nz/#!nM8jHbIS!SxpN74lrxlQeEEPJ7IVqna-qGhQvknXDKvDL78ID6nI

**Comment by haata** [comment]
I believe this was fixed a while ago. Seems to be working now.

http://configurator.input.club/latest/

**Comment by dumle29** [comment]
This doesn't seem to have fixed it. The same layout as above still types 'o'

U"C" : CONS"CALCULATOR"; is the KLL from the configurator.

**Comment by haata** [comment]
kk, I haven't tested the Calculator button yet. I'll test it when I get
back from my business trip.
Just in case you may want to clean out your Windows driver cache (caused me
lots of issues).

**Comment by haata** [comment]
Sorry this took so long.
I've gone through and manually tested all the media keys (there was a kll code generation bug). Should be working now.
I did remove the EDITOR media key (didn't seem to do anything in Linux).

**Comment by dumle29** [comment]
Thanks. Will flash my keyboard with this one :)
