### ISSUE TITLE
colon/semicolon - Firefox Windows 8.1

### ISSUE THREAD

**Issue by smith058** [kiibohd/KiiConf#28]
I'm using the Ergodox layout  on windows 8 - online keyboard layout editor...  The colon key does not register, I can not remap.

**Comment by haata** [comment]
Just to make sure it's not a faulty switch (or badly soldered diode), have you tried remapping that key to something else in the configurator?

**Comment by smith058** [comment]
Thank you for your response,I have replied to your response from Massdrop, bellow is a copy/paste...I can remap it to any other character other than semicolon.I
 set up my board  to use colemak and the default location of semicolon 
needed to change, it does not register the key stroke of the semicolon 
to remap it to another key/position.The problem is not with the ergodox, but either with the web interface configurator or with windows 8.1 and/or Firefox.Thanks-----Original Message-----From: notifications@github.comSent: Mon, 18 Jan 2016 21:01:00 -0800To: kiiconf@noreply.github.comSubject: Re: [KiiConf] colon/semicolon (#28)Just to make sure it's not a faulty switch (or badly soldered diode), have you tried remapping that key to something else in the configurator?

**Comment by haata** [comment]
Interesting that it's an issue with Firefox on Windows 8.1. I'm going to update this bug and leave it open so I can see if I can reproduce it.
