### ISSUE TITLE
Can't map `/~

### ISSUE THREAD

**Issue by obrok** [kiibohd/KiiConf#29]
I'm using http://input.club/configurator-ergodox to configure my ergodox, but can't seem to assign the grave accent / tilde key. I tried putting it in a couple different places, but it always just acts as the backslash / pipe key. Any help would be greatly appreciated

**Comment by haata** [comment]
I suspect this is an issue between your keyboard locale and US ANSI. I have an open issue for adding support for different locales to the configurator (and to KLL) -> https://github.com/kiibohd/KiiConf/issues/14

In the meantime, if you can figure out what key that is on a US ANSI keyboard, that should work for you.

**Comment by OvahKeel** [comment]
Duplicate of issue #14 .
