### ISSUE TITLE
Windows ignores mediakeys

### ISSUE THREAD

**Issue by dumle29** [kiibohd/KiiConf#3]
Media keys work fine in linux (Ubuntu 14.10 Gnome), but when I boot into windows, there doesn't seem to be any scancodes recieved.

This is what I get when I use a generic craptacular HP keyboard:
![image](https://cloud.githubusercontent.com/assets/2756925/7749604/280f3538-ffcf-11e4-897a-e8a452709ba1.png)

The input is captured with [KeyCodes](http://delphiforfun.org/programs/utilities/KeyCodes.htm)

Curiously I'm not getting any keyDown events on Play/Pause, previous or next.

With the Infinity keyboard, I'm not getting any input as far as I can see.

I'm running windows 8.1 pro and Ubuntu-Gnome 14.10

**Comment by dumle29** [comment]
I'm back in linux, and media-keys didn't work in linux either. After reflashing the board with the same image, they now do work.

Odd. I will try to boot into windows again and see if the problem persists.

**Comment by haata** [comment]
That's odd.
So, for Windows, they may be expecting a different media key for the keyboard. Or, a different HID driver (inf file) is expected on windows (Windows is finicky that way). I don't have a Windows computer in front of me right now unfortunately.

**Comment by dumle29** [comment]
So I did some looking around, but I couldn't find any information on what windows would want to see to support media keys.

Without any drivers installed, the keyboard appears both under Other devices, under Keyboards and under the HID tab as well as seen here:

![image](https://cloud.githubusercontent.com/assets/2756925/7799387/ca6fe44c-0305-11e5-98b4-b7fc3e48121c.png)

All of the ones with a red dot have the VID:PID of the keyboard, as seen here:
![image](https://cloud.githubusercontent.com/assets/2756925/7799396/ec3063ea-0305-11e5-8f1a-991d749ede7b.png)

Any ideas on what .inf file would allow windows to recognize the media keys?

I'll quickly try and flash the image to the keyboard from windows and see if that helps.

**Comment by dumle29** [comment]
@haata Okay, so I'm back in linux, and media keys don't work again. After a reflash they do. It seems that using the keyboard in windows, somehow disables the media-keys. I know this sounds insane, but it's happening.

**Comment by flipjs** [comment]
Same here, my volume keybindings are not working in Windows. Will try to bring home the keyboard again and use it in Mac and see if the problem persists.

**Comment by dumle29** [comment]
I did some reading on the subject, and it appears you need to enumerate the keyboard as a consumer device to send media keys.

Someone mentioned Multi-TLC which I assume means the keyboard registers both as a generic keyboard, and as a consumer device. Is this how you are currently handling media keys? http://www.microchip.com/forums/m/tm.aspx?m=618147&p=1

**Comment by flipjs** [comment]
Brought the keyboard back home, all media keys (mute, next track, previous, etc.) are working fine on Mac. I updated the keybindings from CONS to U (as in from CONS"MUTE" to U"MUTE", etc), but still not working on Windows. It could be Windows are using different scan codes. But I'm wondering, what keycodes are being used on some brands of keyboards that work on all different OSes.

**Comment by haata** [comment]
Got this fixed (finally). Too way more effort than it should have. Windows is just super finicky about Media Keys.

I've pushed the updated to the configurator.
