### ISSUE TITLE
_error.zip when using the yen symbol key in the configurator

### ISSUE THREAD

**Issue by domier** [kiibohd/KiiConf#35]
When I add the yen symbol to a layout it generates a file with _error.zip at the end and does not create a layout file. 

Using Chome/windows 10.  I tried several different layouts, but as soon as I add the yen symbol the configurator fails.  Taking it back out also seems to fix the problem.

Example layout here for reproduction: https://input.club/forums/topic/_error-zip-when-using-the-yen-symbol-key-in-the-configurator

**Comment by domier** [comment]
Error log for reference:

'— Build files have been written to: /srv/KiiConf/tmp/371d9d6fea7a5bfc52f985cd534ab045157302376c1df1/right
+ make -j
[ 4%] Generating KLL Layout
[ 4%] Generating KLL Layout
Traceback (most recent call last):
File “/srv/KiiConf/controller/kll/kll.py”, line 758, in <module>
processKLLFile( filename )
File “/srv/KiiConf/controller/kll/kll.py”, line 695, in processKLLFile
data = file.read()
File “/usr/lib/python3.4/encodings/ascii.py”, line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xc2 in position 786: ordinal not in range(128)
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
make: *** [all] Error 2
+ RETVAL=2
+ set +x
Traceback (most recent call last):
File “/srv/KiiConf/controller/kll/kll.py”, line 758, in <module>
processKLLFile( filename )
File “/srv/KiiConf/controller/kll/kll.py”, line 695, in processKLLFile
data = file.read()
File “/usr/lib/python3.4/encodings/ascii.py”, line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xc2 in position 786: ordinal not in range(128)
[ 4%] Generating KLL Layout
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
make: *** [all] Error 2
+ RETVAL=2
+ set +x
[ 4%] Generating KLL Layout
Traceback (most recent call last):
File “/srv/KiiConf/controller/kll/kll.py”, line 758, in <module>
processKLLFile( filename )
File “/srv/KiiConf/controller/kll/kll.py”, line 695, in processKLLFile
data = file.read()
File “/usr/lib/python3.4/encodings/ascii.py”, line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xc2 in position 786: ordinal not in range(128)
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
File “/srv/KiiConf/controller/kll/kll.py”, line 758, in <module>
processKLLFile( filename )
File “/srv/KiiConf/controller/kll/kll.py”, line 695, in processKLLFile
data = file.read()
File “/usr/lib/python3.4/encodings/ascii.py”, line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xc2 in position 786: ordinal not in range(128)
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.elf.dir/all] Error 2
make: *** [all] Error 2
/srv/KiiConf/tmp/371d9d6fea7a5bfc52f985cd534ab045157302376c1df1'

**Comment by haata** [comment]
Ugh, this seems not reproducible on my dev machine...damnit Ubuntu. Let me see if I can whip something up.

**Comment by haata** [comment]
Try now. Seems to work.

**Comment by domier** [comment]
Fix has been implemented
