### ISSUE TITLE
Production firmware build hashes not updating with changes in stats.json

### ISSUE THREAD

**Issue by jbondeson** [kiibohd/KiiConf#41]
Issue turns out to be with the production server not correctly responding to changes in the stats.json.

_Original description_

Cached files are invalid after a controller update and should be purged.

Update the tools scripts to purge pre-build firmware after a successful update.

**Comment by cubiq** [comment]
probably you already know, but hashes are created over the controller version. Technically cached files shouldn't do any harm (apart from taking HD space).

**Comment by jbondeson** [comment]
We had at least one person get the same file we updated the controller. 

More investigation may be needed to see if something is not working exactly right between the environment and download.php.

**Comment by cubiq** [comment]
Related code starts from line https://github.com/kiibohd/KiiConf/blob/master/download.php#L36

Maybe the json file is cached? In which case you could simply add something like

```
$controller_ver = $_SERVER['REMOTE_ADDR'] == '127.0.0.1' || '::1' ? '' : json_decode(file_get_contents('http://configurator.input.club/stats.json?v=t' . time()));
```

**Comment by jbondeson** [comment]
I just verified the bug by altering the stats.json file on the server and it served me the same zip (and hash) from last night. The server is correctly serving up the updated stats.json file.  Might add some debugging information to isolate before making logic changes just to be sure.

I also will be opening an issue to add an "update_kiiconf" shell file as we only update the stats.json when we update the controller, and those two will not always be updated at the same time.

**Comment by cubiq** [comment]
please double check latest commit

**Comment by jbondeson** [comment]
Good catch. Type coercion strikes again! I'll do a quick test on the alpha site and roll to prod this morning.

**Comment by jbondeson** [comment]
Verified and rolled to prod.
