### ISSUE TITLE
Create Colon Key Simple Macro

### ISSUE THREAD

**Issue by CodeMonkeyMike** [kiibohd/KiiConf#43]
In short there is no colon key ":"

The reason this is an issue for me is because I put all my symbols on a function layer and do not wish to hit shift+function+semicolon.

**Comment by jbondeson** [comment]
Seems like a good addition to the 'Simple Macro' list, with the known caveat that it would fail on some international layouts.

**Comment by CodeMonkeyMike** [comment]
I modified the title from "Missing Colon Key" to "Create Colon Key Simple Macro" is that more accurate?

**Comment by jbondeson** [comment]
Perfect. I'll also just go ahead and add the double quote (") as well since that seems to be the only other punctuation missing.

**Comment by jbondeson** [comment]
Currently pushed to [/latest](http://configurator.input.club/latest/) will roll to main production shortly when the WhiteFox layout fixes are verified.
