### ISSUE TITLE
Configurator doesn't add kll files to download

### ISSUE THREAD

**Issue by mattventura** [kiibohd/KiiConf#5]
When using the live version of the configurator (configurator.input.club), even with no modifications to the default layout, the downloaded .zip only contains kiibohd.dfu.bin, and a log folder with build.log, kll_defs.h, generatedKeymap.h, and buildvars.h. 
Looking at the code, it seems like it should have the .kll files included in the archive.

**Comment by haata** [comment]
KLL files work on differences of the configuration to the default.

If you open the generatedKeymap.h file it has debug comments which give the absolute paths (and order of inclusion, which matters) to all of the kll files to generate it. Most of them are static and never change.

For example
````c
// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2015-05-10
// KLL Backend:        kiibohd
// KLL Git Rev:        d05f7ae8204841268e44d4c199416c3c0da4dd33
// KLL Git Changes:
//    kll.py
//    layouts/md1Overlay.kll
// Compiler arguments:
//    ../kll/kll.py
//      /home/hyatt/Source/controller/Scan/MatrixARM/capabilities.kll
//      /home/hyatt/Source/controller/Macro/PartialMap/capabilities.kll
//      /home/hyatt/Source/controller/Output/pjrcUSB/capabilities.kll
//      /home/hyatt/Source/controller/Scan/MD1/defaultMap.kll
//      -d
//      /home/hyatt/Source/controller/kll/layouts/md1Overlay.kll
//      /home/hyatt/Source/controller/kll/layouts/stdFuncMap.kll
//      -p
//      /home/hyatt/Source/controller/kll/layouts/hhkbpro2.kll
//    --backend
//      kiibohd
//    --templates
//      /home/hyatt/Source/controller/kll/templates/kiibohdKeymap.h
//      /home/hyatt/Source/controller/kll/templates/kiibohdDefs.h
//    --outputs
//      generatedKeymap.h
//      kll_defs.h
//
// - Base Layer -
//    MatrixArmCapabilities
//      /home/hyatt/Source/controller/Scan/MatrixARM/capabilities.kll
//    PartialMapCapabilities
//      /home/hyatt/Source/controller/Macro/PartialMap/capabilities.kll
//    pjrcUSBCapabilities
//      /home/hyatt/Source/controller/Output/pjrcUSB/capabilities.kll
//    MD1
//      /home/hyatt/Source/controller/Scan/MD1/defaultMap.kll
// - Default Layer -
//    md1Overlay
//      /home/hyatt/Source/controller/kll/layouts/md1Overlay.kll
//    stdFuncMap
//      /home/hyatt/Source/controller/kll/layouts/stdFuncMap.kll
// - Partial Layers -
//    Layer 1
//     hhkbpro2
//       /home/hyatt/Source/controller/kll/layouts/hhkbpro2.kll
````

I could include all of the files with the zip file, but it's pretty redundant if the .kll files are available in git repository.

In the future I'll be adding a "top-level" .kll file which will make inclusion and building a lot more straight-forward that dealing with CMake.

**Comment by mattventura** [comment]
Oh, I see now. If a layer is enabled but isn't actually changed off the default, then it won't include it. I thought it was just not including them, period.
