### ISSUE TITLE
What version/branch of kiibohd/controller does http://configurator.input.club/ use?

### ISSUE THREAD

**Issue by chrismetcalf** [kiibohd/KiiConf#6]
I can't get the `.kll` files that I downloaded with my compiled `.bin` to recompile using the master branch of `kiibohd/controller`. My media keys aren't recognized and it seems confused by my layer mod keys.

Any advice? I just want to rebuild and version control what I created with http://configurator.input.club/.

**Comment by haata** [comment]
I haven't updated the configurator code in a while (I still need to test compatibility of master more before pushing updates).

You can find the info you need here http://configurator.input.club/stats.json

**Comment by chrismetcalf** [comment]
Thanks! Getting the proper version of kll fixed my issues, and I'm up and building now. Thanks!
