### ISSUE TITLE
'~' being output as '¬'

### ISSUE THREAD

**Issue by Nalum** [kiibohd/KiiConf#67]
I've loaded [this config](https://gist.github.com/Nalum/3a7bbbb2574d0160d4d2265cf3e87a56) into my Ergodox Infinity and as the title says `~` is being output as `¬`. Not sure if that is an OS level issue or something wrong in the configurator.

Pressing the `¬` key on my keyboard appears to clear the value of the key selected in the configurator.

**Comment by gibfahn** [comment]
I had this issue, and it turned out to be due to my OS's language settings (I was using English UK instead of English US). AFAIK the `~` is actually just a macro that does `Shift+Backtick` (or whichever the key combo is). What the OS interprets that as depends on the language setting.
