### ISSUE TITLE
Configurator/Controller function name mismatch

### ISSUE THREAD

**Issue by hbaughman** [kiibohd/KiiConf#68]
I used [the configurator](https://configurator.input.club/?layout=MDErgo1-Default) to generate most of my layout, then copied the downloaded files into `Controller/kll/layouts`. They were *not* compatible with the default `lcdFuncMap.kll` which uses different function names (outlined below). This causes the build to fail.

I was able to resolve this with a search-and-replace in the `lcdFuncMap`, but I feel that the configurator should be as compatible as possible with the Controller.

```
Controller | Configurator
-----------+-------------
Function1  | FUN1
Lock1      | LCK1
Latch1     | LAT1
```

**Comment by jbondeson** [comment]
I'm going to need a little more info on exactly the steps you performed, as the configurator simply calls a bash script to compile the firmware with the kiibohd/controller project.

**Comment by hbaughman** [comment]
I'm having trouble generating a test case. I was fighting another issue with Controller yesterday (since resolved), and I suppose this solution was somehow related to that. Apologies for the trouble.

**Comment by jbondeson** [comment]
No worries, if you stumble upon it again just reopen and I can take a look.
