### ISSUE TITLE
keys not registering for Mac OS 10.12.2 (Sierra)

### ISSUE THREAD

**Issue by mendokusai** [kiibohd/KiiConf#69]
For whatever reason these following keys will not register, regardless of which switch matched to:

```
<space>, <comma>, <period>, </question>, <colon>, <apostrophe>,
<left-bracket>, <right-bracket>, <hyphen>, <equals>, <backtick>,
<delete>, <page up>, <page down>, <left/right/up/down arrows>
```

I can even set any key to the switches (i.e. “A” on the spacebar) and it will give me “A”s for days, but if I set “[ ]” to a “V” I get nothing.

**However** If I type a working key and a non-working key at the same time or in quick A-B typing, I can sometimes get the non-working key to register. I've yet to try to build from local, but will try that next

**Comment by jbondeson** [comment]
Are you running Karabiner? Many of the mac issues have been tracked back to it.

If not the next step is to use screen to debug codes coming down the pipe.

**Comment by mendokusai** [comment]
I installed Karabiner-Elements *after* this issue in hopes it could override my issue, but no.

Will look into screen.

**Comment by jbondeson** [comment]
Here's the docs for debugging https://github.com/kiibohd/controller/wiki/Debugging

What you want to look for are the codes coming across to see if it's the firmware or something on the OS side.

**Comment by mendokusai** [comment]
Sorry to sidebar-question, but I'm unable to find the `tty.<usb something>` related code. Had tried various combinations of the `"USB Serial Number" = "B1E1000068D1000B0038500F28964E45 - mk20dx256vlh7"` for my devise, but they're not getting me anywhere.

**Comment by mendokusai** [comment]
This is the whitefox kit from the latest Massdrop run.

**Comment by mendokusai** [comment]
Here's most of the keys. Getting up and down was a bit difficult as it wanted to change inputs.

#### KII Codes
- < space > `0x20`
- < , > `0x2C`
- < . > `0x2E`
- < > > `0x3E`
- < < > `0x3C`
- < / > `0x2F`
- < ? > `0x3F`
- < ; > `0x3B`
- < : > `0x3A`
- < ' > `0x27`
- < " > `0x22`
- < [ > `0x5B`
- < { > `0x7B`
- < ] > `0x5D`
- < } > `0x7D`
- < - > `0x2D`
- < \_ > `0x5F`
- < = > `0x3D`
- < + > `0x2B`
- < \\ > `0x5C`
- < | > `0x7C`
- < \` > `0x60`
- < ~ > `0x7E`
- < delete > `0x1B 0x5B 0x33 0x7E`
- < page up > `0x1B 0x5B 0x35 0x7E`
- < page down > `0x1B 0x5B 0x36 0x7E`
- < left arrow > `0x1B 0x5B 0x44`
- < right arrow > `0x1B 0x5B 0x43`
- < up arrow > `0x1B 0x5B 0x31 0x3B 0x32 0x41` (Lshift + up)
- < dn arrow > `0x1B 0x5B 0x31 0x3B 0x32 0x42` (Lshift + dn)

As noted originally, these codes didn't show unless I typed them in conjunction with a 'working' key. Touching the key by itself would register no code.

**Comment by haata** [comment]
Hmm, this is interesting.

I'm not sure if this is a USB descriptor (OS issue) or a hardware problem.
Let's try ruling out the hardware first.

1. Plug into a different computer and see if the same issue occurs (preferably not macOS, but not too important)
2. Get the debug cli working https://github.com/kiibohd/controller/wiki/Debugging and then type the matrixDebug command. Now when you press a key, a number will show up (that is the internal scan code). Press each key one (specifically the keys that you are having troubles with). If any keys do not show up, this is a hardware problem.

If (2) seems to be working correctly (each key has a unique number, and only one number), then we can rule out a hardware issue.

**Comment by mendokusai** [comment]
So I've already plugged the keyboard into my other apple laptop running Yosemite and the keyboard works a treat. Every key works exactly as it should.

I've done some research, specifically reading through Karabiner issues and what's happened is that Apple has re-written the keyboard drivers for MacOS Sierra. I've been hunting for specific documentation on these keyboard drivers, but I've yet to find something. I'll go ahead and run the debug on the other machine to compare, but I'll keep looking for info on the new Sierra driver...

**Comment by mendokusai** [comment]
I've discovered a solution. If one does a [SMC reset](https://support.apple.com/en-us/HT201295) the computer sorts itself out. 

> restart computer and hold down `shift` + `control` + `option`+ `start` for five seconds, release keys and start computer. 

Super odd, but it works and **I'm typing with my keyboard now**

Thanks for assistance @jbondeson @haata

![typing](http://s1.dlnws.com/files/uploads/batman-typing.png)
