### ISSUE TITLE
Missing key for Danish layout on WhiteFox

### ISSUE THREAD

**Issue by r3Fuze** [kiibohd/KiiConf#70]
I have a problem configuring my ISO WhiteFox.. By default the key to the bottom left of the Enter key is bound to APP, but on the Danish layout I need it to type ' when I don't hold shift and * when I do.

Here's an image of the Danish layout:

http://i.imgur.com/kODJAP9.png

I'm not sure if I'm just missing the key on the configurator or if it is not there at all.

**Comment by jbondeson** [comment]
You should be able to map it to ISO# (first key under the "international" section) to get that effect with Danish.

With int'l layouts you set the values to what the key in the same location on an US-ANSI keyboard are, and with the two extra keys you use ISO# (near the enter) and ISO/ (near the left shift). 

I will add an issue to default this properly on the WhiteFox ISO layout.

**Comment by r3Fuze** [comment]
I just tried the ISO# key, but now the button just does nothing. I changed some other keys to make sure the flash went through.

This is what the layout looks like right now:
http://i.imgur.com/58A8jLj.png

Let me know if there's any other information you need.

**Comment by jbondeson** [comment]
Oh, I totally forgot about the issue with Linux and ISO# (there's an issue with NKRO on Linux when you have the ISO# in the message). You're going to have to put it into 6KRO mode.

Try and throw the 6/N-KRO button on a layer and switch to it so see if you can get that to output. If that works there are ways to get it to stay in boot mode.

I'll also talk to @haata about removing the restriction for that key.

**Comment by r3Fuze** [comment]
Sorry, I should probably have said that I'm on Windows. Do I still need to do switch KRO mode? If I do where would I do it? I'm pretty new to this.

**Comment by jbondeson** [comment]
Yes, currently if in NKRO mode the ISO# key will not be sent on any OS.

To test this put the "6/N-KRO" key (the last key in the "special" group) on a function layer (say fn+esc) and after plugging in the keyboard hit the key combo and try using the ISO# key again.

**Comment by r3Fuze** [comment]
Ah, that did it. Thanks a lot :)

**Comment by jbondeson** [comment]
If you'd like to have this start in 6KRO mode (so you don't have to keep hitting that button every time) go to http://configurator.input.club/alpha (this is the in-progress version) and go to the "kll defines" section and hit the `+` button and in "Name" put in `usbProtocol` and the "Value" put `0`. 

After that go ahead and configure the layout you'd like. You can also add that `N/6-KRO` key on a layer if you want to have NKRO for something like gaming.
