### ISSUE TITLE
 How should i do to add international symbols to funktion layers ?

### ISSUE THREAD

**Issue by Belfaz** [kiibohd/KiiConf#71]
so i would like to add these: ([ñ] [ç] [å] [ä] [ö] [¨]) to a function layer, how would i go about doing that ?

i hav ethe white fox true fox keyboard

**Comment by jbondeson** [comment]
What is the language setting for your OS?

**Comment by Belfaz** [comment]
it is in english, i know that by setting the keyboard to swedish/other languages i can basically use other layouts with these symbols, but my intention was/is to be able to have them in another layer, so i can use them just when i need them.

**Comment by jbondeson** [comment]
Unfortunately there's not a cross platform way to output arbitrary characters. Most likely to work solution would be to have a macro that outputs the code (for Windows that would be Alt plus a sequence of keypad numbers). Unfortunately there is no macro support in the GUI configurator yet, but this has become more common so I may just bang out a "good not great" solution until I get more time to do something better.  You could configure all other keys, get the resulting kll files and then manually compile.

We do have a few ideas in the works to make this easier, but nothing imminent.

**Comment by Belfaz** [comment]
okey Thank you
good to know that the problem is not completely uncommon, it is not a deal breaker for me since i rarely need these symbols apart from when i am typing in those languages, so i can easily switch inputs, it is just that i felt that it would be cool to just use on input language and combine the characters in function layers since it is my firs keyboard with multiple layers. i will be keeping an eye out for updates on the GUI. thanks again for the awesome  help !

**Comment by Belfaz** [comment]
NOw that i have you, may i ask one more thing ? the media shortcuts in the OSX dont seem to function [PREV] [PL/PS] [Next], is there somthing i am doing wrong, i recently noticed
