### ISSUE TITLE
New configurations generated for Ergodox Infinity have issues updating the LCD layer indicator on the 'slave' hand

### ISSUE THREAD

**Issue by fergusonna** [kiibohd/KiiConf#72]
On a new configuration I created today, after flashing the left and right hands, the slave hand doesn't change layers when pressing a layer change key on the master, and vice versa. Only the master will correctly change layer. The LCD on the slave dims, and nothing else. 

It doesn't matter which hand is the slave. If each hand is connected directly to the PC, the layer will change correctly. 

Loading an older configuration, created on February 12th, 2017, the layer changes correctly on both hands, slave and master. 

[Working configuration: 02122017MDErgo1-Default-809090f631efafa017c6daa0ce46b6ab.zip](https://github.com/kiibohd/KiiConf/files/788713/02122017MDErgo1-Default-809090f631efafa017c6daa0ce46b6ab.zip)

[Failing configuration: MDErgo1-PostFix.zip](https://github.com/kiibohd/KiiConf/files/788714/MDErgo1-PostFix.zip)

**Comment by jbondeson** [comment]
Fixed and updated (SEE: https://github.com/kiibohd/controller/commit/220632184329f06a4f9f8e6a5317d23e7305bd7e ) . Thanks for the patience.
