### ISSUE TITLE
how do I get it to show the default layout?

### ISSUE THREAD

**Issue by jtmkrueger** [kiibohd/KiiConf#73]
Here's what I see when I visit the page: https://www.dropbox.com/s/vnrsd5sjugqt49a/Screenshot%202017-02-23%2009.05.07.png?dl=0

How do I get the default layout to load so I can see the keys?

**Comment by OvahKeel** [comment]
What OS / version? If you select other layouts from the drop down, do they work? What internet browser are you using?

**Comment by jtmkrueger** [comment]
Looks like this is a chrome bug. It works just fine in firefox. I'm on a mac.

**Comment by jtmkrueger** [comment]
@OvahKeel none of the other layouts work either.

**Comment by jbondeson** [comment]
@jtmkrueger My guess it an extension or setting is messing with you. The configurator makes a few calls to the backend to get data to render, I'm wondering if something is getting messed up along the way. I would be interesting to see the output of the developer console and network. You could also try it in incognito mode which should disable most of the extensions.

**Comment by jtmkrueger** [comment]
so here it is in incogneto mode: https://www.dropbox.com/s/6md45r8yq9vozxz/Screenshot%202017-02-23%2010.45.26.png?dl=0

Looks like it's related to local storage somehow?

**Comment by jbondeson** [comment]
@jtmkrueger yeah, you must have chrome set to block sites from setting data. You'll have to enable it in Settings->Privacy->Content settings->Cookies->Manage exceptions.

**Comment by jtmkrueger** [comment]
Ah, yep that was the issue. Thanks for helping me figure that out.

**Comment by jtmkrueger** [comment]
It might be helpful for idiots like me if there was some sort of alert that popped there to let people know that they needed to fix a setting.

**Comment by jbondeson** [comment]
Yep, opened #74 just for that :)
