### ISSUE TITLE
Not recieving activation email

### ISSUE THREAD

**Issue by jtmkrueger** [kiibohd/KiiConf#75]
I've tried a couple times to have it resent, but the email isn't getting to me. I know I put in the right email, because it looks right in my password manager, and I get the error that I haven't activated yet when I use my email instead of my username.

**Comment by parak** [comment]
linux.com has some antispam measures in place that apparently cannot lookup "input.club" properly, so the email is being rejected. There's probably some sort of a misconfiguration on their end that fails to consider .club tld as valid or something - first time I've seen this particular type of rejection! I'd suggest asking them about it (if you happen to know who to ask), but in the meantime I manually enabled your account :)

**Comment by jtmkrueger** [comment]
Thanks @parak !

I sent an email out to their tech support about it. we'll see what happens.
