### ISSUE TITLE
F17, F18, F19

### ISSUE THREAD

**Issue by jordanmarchetto** [kiibohd/KiiConf#80]
Is it possible to map keys to f17-f19?

**Comment by jbondeson** [comment]
Yes F17-F24 are available, however they are not shown in the UI. A way around that is to map those keys to something you can find but don't use in your map, then download the firmware. In the zip file will be a `.json` file which you could manually change to the F17-24 keys as you see fit. Copy the contents of the modified file and hit the "Import Map" button, paste in in and import. The UI should now show you your F17-F24 keys

Not a super simple workaround, but I can open an issue to put the "not normal, but not insane" keys into some kind of "other" group.

**Comment by jordanmarchetto** [comment]
Ah, I never noticed the input map button.

This worked for me, thank you.
