### ISSUE TITLE
"none" special key make compiler crash

### ISSUE THREAD

**Issue by benoittgt** [kiibohd/KiiConf#83]
Hello

With a kll like:
```
Name = "MDErgo1";
Layout = "Default";
Base = "Blank";
Version = "0.1";
Author = "HaaTa (Jacob Alexander) 2015";
KLL = "0.3c";
Date = "2015-09-12";
Generator = "KIICONF 0.2";

U"FUNCTION1" : None;
```
Ergodox bash script : 
```sh
-- Build files have been written to: /Users/bti/code/controller/Keyboards/darwin16.miami_ergodox_r.gcc.make
[  3%] Generating KLL Layout
kll BETA 0.5c.54d839fa7a8dcd4352da10288512036a54e247dc - 2017-10-21 16:11:42 +0200
Traceback (most recent call last):
  File "../../kll/kll", line 159, in <module>
    control.process()
  File "/Users/bti/code/controller/kll/common/stage.py", line 123, in process
    stage.process()
  File "/Users/bti/code/controller/kll/common/stage.py", line 2827, in process
    self.emitter.process()
  File "/Users/bti/code/controller/kll/emitters/kiibohd/kiibohd.py", line 671, in process
    self.fill_dict['ResultMacros'] += "{0}, ".format(self.result_combo_conversion(combo))
  File "/Users/bti/code/controller/kll/emitters/kiibohd/kiibohd.py", line 249, in result_combo_conversion
    cap_index = self.capabilities_index[identifier.name]
KeyError: 'None'
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.dir/all] Error 2
make: *** [all] Error 2
Error in make. Exiting...
```

**Comment by mendhak** [comment]
Noticing the same on the web based configurator - I tried to make the caps-lock key `NONE` on the K-Type keyboard; the firmware downloaded is suffixed with _error and the log file (attached)  contains

> FAILED: cd /srv/KiiConf/tmp/687ce01335aae2ebe18e573e4acf904e159f8c218dad20 && /srv/KiiConf/controller/kll/kll --version && /srv/KiiConf/controller/kll/kll --config /srv/KiiConf/controller/Scan/Devices/ISSILed/capabilities.kll /srv/KiiConf/controller/Scan/Devices/MatrixARM/capabilities.kll /srv/KiiConf/controller/Scan/Devices/PortSwap/capabilities.kll /srv/KiiConf/controller/Scan/Devices/UARTConnect/capabilities.kll /srv/KiiConf/controller/Macro/PartialMap/capabilities.kll /srv/KiiConf/controller/Macro/PixelMap/capabilities.kll /srv/KiiConf/controller/Output/HID-IO/capabilities.kll /srv/KiiConf/controller/Output/pjrcUSB/capabilities.kll --base /srv/KiiConf/controller/Scan/K-Type/scancode_map.kll --default /srv/KiiConf/controller/kll/layouts/stdFuncMap.kll KType-Standard-0.kll --partial /srv/KiiConf/controller/kll/layouts/stdFuncMap.kll KType-Standard-1.kll --emitter kiibohd --def-template /srv/KiiConf/controller/kll/templates/kiibohdDefs.h --map-template /srv/KiiConf/controller/kll/templates/kiibohdKeymap.h --pixel-template /srv/KiiConf/controller/kll/templates/kiibohdPixelmap.c --def-output kll_defs.h --map-output generatedKeymap.h --pixel-output generatedPixelmap.c --preprocessor-tmp-path /srv/KiiConf/tmp/687ce01335aae2ebe18e573e4acf904e159f8c218dad20/tmp_kll
kll BETA 0.5c.f0f1032e4690f103be99d616c17d0c22a2a7633c - 2017-10-14 15:44:22 -0700
Traceback (most recent call last):
  File "/srv/KiiConf/controller/kll/kll", line 159, in <module>
    control.process()
  File "/srv/KiiConf/controller/kll/common/stage.py", line 123, in process
    stage.process()
  File "/srv/KiiConf/controller/kll/common/stage.py", line 2827, in process
    self.emitter.process()
  File "/srv/KiiConf/controller/kll/emitters/kiibohd/kiibohd.py", line 671, in process
    self.fill_dict['ResultMacros'] += "{0}, ".format(self.result_combo_conversion(combo))
  File "/srv/KiiConf/controller/kll/emitters/kiibohd/kiibohd.py", line 249, in result_combo_conversion
    cap_index = self.capabilities_index[identifier.name]
KeyError: 'None'
ninja: build stopped: subcommand failed.
Error in make. Exiting...

[build.log](https://github.com/kiibohd/KiiConf/files/1431884/build.log)

**Comment by jbondeson** [comment]
This is fixed in this commit: https://github.com/kiibohd/kll/commit/aad5145b12c0cb8dd207d4c00585a9c71256612d

I will update the configurator shortly.
