### ISSUE TITLE
Generated TrueFox layout on Whitefox Aria

### ISSUE THREAD

**Issue by zhaoyangyang316** [kiibohd/KiiConf#85]
When I flash the firmware from latest version to the  Whitefox Aria (Batch 1), the layout seems to become Truefox.  e.g. some keys don't work and backspace and backslash swapped.

**Comment by zhaoyangyang316** [comment]
I used this configurator. : https://configurator.inputclub.com/

This is the generated firmware 
https://drive.google.com/file/d/0B9Y8J0Wpewn2MUxYSWhlMUJxaFk/view

**Comment by zhaoyangyang316** [comment]
Actually I found a version which works: https://configurator.input.club/alpha/?layout=WhiteFox-AriaBlank

But better to fix this problem for the new user not to get  confused :)

**Comment by compuguy** [comment]
Would this bug have any relation to #93 ?

**Comment by zhaoyangyang316** [comment]
Just found out this is still open, so here is the quick update: couple days after I filed this issue the keyboard is unusable again. 

I gave up and using a FC660M now.

**Comment by jbondeson** [comment]
This has been fixed and confirmed with a first batch Aria. Tested in both web and clientside.
