### ISSUE TITLE
[Whitefox ISO] Only LED toggle (or On/Off) seems to work.

### ISSUE THREAD

**Issue by DarkDefender** [kiibohd/KiiConf#87]
I wanted to try out the new firmware today and see if the new led animation stuff would work.

However, now only toggling the leds on/off seems too work. LED+/- and the "25%" keys doesn't do anything for me. The leds seems to always be at 100%.

The led animation keys (the "V:" keys) doesn't seem to do anything either. Now, I know that the whitefox only comes with one default animation, but I can't seem to get it to play...

**Comment by kevinleguillou** [comment]
I've encountered the same issue, but to be more specific : 

Building using "latest firmware" (https://input.club/configurator/), when I trigger a `MULTIMEDIA_NEXT` action using my shortcut `ƒ1`+`→` every key becomes unresponsive.

Only `LED_TOGGLE` works (which I bound to `ƒ1`+`BACKSPACE`). Only fix is to unplug-replug keyboard.

Here is the build in question : [WhiteFox-IsoBlank-268df48251aad5f867d98a9daf775ff5.zip](https://github.com/kiibohd/KiiConf/files/1663443/WhiteFox-IsoBlank-268df48251aad5f867d98a9daf775ff5.zip)

@DarkDefender I've recompiled the firmware using the "lts" option on the configurator, LED Toggle isn't supported but at least the keyboard works, if you have any problems use this in the meantime.

**Comment by DarkDefender** [comment]
@kevinleguillou glad to know there are other people that have the same problem as me. :)
Then it probably isn't a hardware issue.

Regarding the ƒ1+→ combo, I've already opened an issue about that #88 . But I thought it was because of numpad 3. But my numpad 3 is bound to ƒ1+→ so I guess that is the root of the problem!

**Comment by kevinleguillou** [comment]
I've also found out that if I press the `→` key alone when the keyboard is unresponsive, everything unlocks/rework. (But the combination itself still doesn't work.)

**Comment by DarkDefender** [comment]
This is now solved for me with the latest firmware.

**Comment by kevinleguillou** [comment]
Indeed, I regenerated a .bin using the configurator and it works like a charm !
